
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL-false
    username: root
    password: root

#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect




